<?php
/**
 * @category    Yoochoose
 * @package     Yoochoose-JSTracking
 * @copyright   Copyright (c) 2015 Yoochoose GmbH. (http://www.yoochoose.net)
 */
?>

<script type="text/javascript">
    //<![CDATA[
    function yc_configure_auth() {
        new Ajax.Request('<?php echo $this->getAjaxConfigureUrl() ?>', {
            method: 'get',
            onSuccess: function (transport) {
                var data;
                if (transport.responseText) {
                    data =  JSON.parse(transport.responseText);
                    document.getElementById('yoochoose_data_export_consumer_name').value = data.consumerName;
                    document.getElementById('yoochoose_data_export_consumer_key').value = data.consumerKey;
                    document.getElementById('yoochoose_data_export_consumer_secret').value = data.consumerSecret;
                    document.getElementById('yoochoose_data_export_rest_role').value = data.restRole;
                }
            }
        });
    }
    //]]>
</script>

<?php echo $this->getButtonHtml() ?>